language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
before_script: wget https://raw.githubusercontent.com/osTicket/core-plugins/develop/make.php
env:
  - CROWDIN_PROJECT="osTicket-auth-cas"
  - secure: qjdQmFzIdCSOGZd7BX0j/c5rOUjD6M9v8++Iz84adZnCgwk1FT9FA7d+H9h4IdJUdUjvhNRo8ne1PjMgIlD9169/KFEKl1yX/2WDQadlIawNHHFN7zpU3y19D4oReNExhhANuZ/NouPl6j5Ug4RHH0y6zsxltRT5I78Q/scAYXXb4ReZoQMQutAdKfc572s/BPLobgPcbbamX7suSak5o4+MXxSnLtfrOTqm7fkztad/MhvIdijiax311hOY00T7S4fVQfoNbk7z6gaqs2d7gqN5WRVu7Vjgm2H2/oj1KJjFx033r0WvW3NNCFCuZyc2UWyeypQBLvXjGMwVTrBV92hhFvQlkVpSiAxVGNdlkSJlwIbbNtGyoqinGv4nsKNwqnKQY24RBcJ+bY3dGZC91KlXTX060UQO1mvvsVpbEyXSEvPfaM1OzNqfuScpmMzAv3UzE0hk8AoVCCkDuxy9CsHqwBEBtnTa5CxsiPQw1XqqpXyNhonr3BhHa19Ulk7IBn+TBbehVdtgIiPToRJolvPxyQ5Ii6XafqXbgyzXJnSqBmZYNgzAC1OfB6EXrKh3cjkygiE2KVndUYsKMwIKbdApImgGLWhcrDDAPjZDkS/gPpvbmYBtmJbpC5RMr7pPEXcE8l+uIwo9sDwiyphlaP8G1yHvxVQuL+xszO+Snww=
script: php make.php build auth-cas
deploy:
  provider: releases
  api_key:
    secure: QxUFyDsWH/kY5dOai1KiqUwrfJ4pHXQ5isuW7Cl/fLSqPA//mfxKLx+feIdve6ya7SbsgR1VvXBJijinW9juq8wn0LxT4Ntji9x3ZHvqYOMV4FiY2mAgvPSzTYpcSTsEhZCsCwY0vLtue5o4cQu2GXGX5WdZMvt0eOCdPenrEG8snF4S9j8Gpah5aPLYGXPAJGLeh+d472D9LUKHqrw7cUMQB8ry2X2hyiu00I06bChwjg8M0Ph0svyXQGr4CPAIv2xokIaIT8/UYeP6Ga7a/NsaCrvxSnp+LkOgCjaTIF9IaKtunB+XWQtL1izqu9nJJ4xWock7Ublu/9ClnVNMIPyHawaN8FnLBTv3oGdijcdCnPYoTiiB7/YhlPVAXBT1CKkFFVdITODlGnFSIqtOHJrZHYjunwyhbNePIGTz31P1KYwIOJ/asrMGQJN46KHbL+dWSKzOZNamYQJZziW5WFg0t6vlXVSH9yHC1gLpSQRD9zD7s4lj2xLM0X9qTkRFaA9lVqV3hZcsMCltEJJVN+PkfuN9BLXSSe4ldTu8NJnILnvZtLPdAeISPFACcsk33BYhd54xkDoLs9MtvEQOey7VwozD4/rVr/WBjBDqxFLHvC3O6cZCI4ryyVNNeTfM6eAa7ALxEimJ+NaCsR66V41GgYsg8PDwf76sjUzr6rQ=
  file: auth-cas.phar
  skip_cleanup: true
  on:
    repo: kevinoconnor7/osTicket-auth-cas
    tags: true
